### ISSUE TITLE
vendors entity URL path issue

### ISSUE THREAD

**Issue by shrexster42** [davidmoten/microsoft-dynamics-finance-client#1]
Hi @davidmoten 

Thanks for the help on creating this client with the Microsoft dynamics Finance and Operations metadata

I was trying out the client and queried the dynamics instance to get a vendor present there. The URL is below. `{{resource}}` is the dynamics instance

`GET /{{resource}}/data/Vendors(dataAreaId='usrt',VendorAccountNumber='BR0001')?cross-company=true`

I used the client as below

```
client
	  .vendors("usrt","BR0001")
	  .query("cross-company","true")
	  .get().getAddressDescription().ifPresent(System.out::println);
```
After obtaining the client credentials token, the client is sending the request as below which is resulting in a 404

`https://{{resource}}/data/Vendors/usrt/BR0001?cross-company=true`

Anything I can do on the methods to reflect the OData format required for the Vendors entity?

Thank you

**Comment by shrexster42** [comment]
I debugged the code and see the `PathStyle` being set to `PathStyle.IDENTIFIERS_AS_SEGMENTS`

I am looking for a way to override this default and use `PathStyle.IDENTIFIERS_IN_ROUND_BRACKETS`.

I see this method to set path style on `BuilderBuilder2`. Happy to submit a PR if you can tell me which builder this setting can go into on the other Builder which results from `Dynamics.service(Resources.class)`

```
       /**
         * Sets the path style. Default is {@link PathStyle#IDENTIFIERS_AS_SEGMENTS}.
         * @param pathStyle path style to use
         * @return this
         */
        public BuilderBuilder2<T> pathStyle(PathStyle pathStyle) {
            this.pathStyle = pathStyle;
            return this;
        }
```

**Comment by davidmoten** [comment]
Yep, no problem I'll ensure the pathStyle is accessible in the Dynamics builder and we should be sorted.

**Comment by davidmoten** [comment]
Sorted, committed to master, [DynamicsMain.java](https://github.com/davidmoten/microsoft-dynamics-finance-client/blob/master/src/test/java/com/github/davidmoten/ms/dynamics/DynamicsMain.java) updated to show usage.

**Comment by shrexster42** [comment]
Thanks very much @davidmoten for the change.

The fetch from vendors entity works as expected now with the `PathStyle.IDENTIFIERS_IN_ROUND_BRACKETS` setting

**Comment by davidmoten** [comment]
Great. No worries.
